[project]
name = "finansai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.11.3",
    "matplotlib>=3.10.3",
    "mplfinance>=0.12.10b0",
    "streamlit>=1.45.1",
    "yfinance>=0.2.61",
]
